name: Build_Ubuntu_x86-64

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main source code
      uses: actions/checkout@v2
      with:
        ref: ci
        fetch-depth: 0

    - name: Build environment initialization
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Updating and installing system packages..."
        sudo -E apt-get update
        sudo -E apt-get -y install doxygen graphviz zstd

    - name: Build docs
      run: |
        mkdir doxygen_output
        doxygen

    - name: Tar docs
      run: |
        sh -c 'tar -c -f - doxygen_output | zstdmt > doxygen_output.tar.zst'

    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: Docs
        path: doxygen_output.tar.zst
